### ISSUE TITLE
Usage of different additional channel

### ISSUE THREAD

**Issue by wzx16** [jimmyyhwu/spatial-action-maps#1]
Hi,

Very impressive work and thanks for sharing the code! 

I have a question regarding your code. Could you explain different options of the additional channel of the get_state function in environment.py? For example what's the pro and con? 
https://github.com/jimmyyhwu/spatial-action-maps/blob/f5d51e98555b84ba2ff40581c04f76967d8c825f/environment.py#L1033

Thank you!

**Comment by jimmyyhwu** [comment]
That's a great question!

Typically we use `use_shortest_path_to_receptacle_channel` and `use_shortest_path_channel`. You can check Section IV-A in the paper, the paragraph on "Effect of shortest path input channels", for ablation experiments with those two channels.

For an environment with no obstacles in the room, you can use `use_distance_to_receptacle_channel` and disable `use_shortest_path_channel`, since without obstacles, shortest path is equivalent to Euclidean distance.

The `use_position_channel` option is only used for the steering commands baseline.

Hope this helps!

**Comment by jimmyyhwu** [comment]
For the values we used in our experiments, see the config files [here](https://github.com/jimmyyhwu/spatial-action-maps/tree/master/config/experiments/base).

**Comment by wzx16** [comment]
Great thanks for that Jimmy! I don't have any other question regarding this topic so I am closing this issue. Stay well.
